"""initial tables

Revision ID: 9d2e18d90b25
Revises:
Create Date: 2026-03-29 16:51:47.677494

"""

from typing import Sequence, Union

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9d2e18d90b25"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "environment_requests",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("requester_name", sa.String(length=100), nullable=False),
        sa.Column("requester_email", sa.String(length=255), nullable=False),
        sa.Column("team", sa.String(length=100), nullable=False),
        sa.Column("env_name", sa.String(length=100), nullable=False),
        sa.Column(
            "env_type",
            sa.Enum(
                "DEVELOPMENT", "TESTING", "STAGING", "RESEARCH", name="environmenttype"
            ),
            nullable=False,
        ),
        sa.Column(
            "os_type",
            sa.Enum(
                "UBUNTU",
                "DEBIAN",
                "CENTOS",
                "FEDORA",
                "WINDOWS",
                "MACOS",
                name="ostype",
            ),
            nullable=False,
        ),
        sa.Column("os_version", sa.String(length=50), nullable=False),
        sa.Column("cpu_cores", sa.Integer(), nullable=False),
        sa.Column("ram_gb", sa.Integer(), nullable=False),
        sa.Column("storage_gb", sa.Integer(), nullable=False),
        sa.Column("required_tools", sa.Text(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "PROVISIONING",
                "ACTIVE",
                "EXPIRED",
                "CANCELLED",
                name="requeststatus",
            ),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=100), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_requests")),
    )
    op.create_index(
        "ix_env_requests_status_created",
        "environment_requests",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_environment_requests_requester_email"),
        "environment_requests",
        ["requester_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_environment_requests_status"),
        "environment_requests",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_environment_requests_status"), table_name="environment_requests"
    )
    op.drop_index(
        op.f("ix_environment_requests_requester_email"),
        table_name="environment_requests",
    )
    op.drop_index("ix_env_requests_status_created", table_name="environment_requests")
    op.drop_table("environment_requests")
    # ### end Alembic commands ###
